### ISSUE TITLE
app request : xfce4-power-manager, need to control brightness to laptop

### ISSUE THREAD

**Issue by newyorkthink** [xplshn/AppBundleHUB#1]

**Comment by xplshn** [comment]
Added the build recipe, should be available in a few minutes when the GH bot finished building.
Let me know if it works!

**Comment by newyorkthink** [comment]
> Added the build recipe, should be available in a few minutes when the GH bot finished building. Let me know if it works for you! EDIT: CI is failing, will fix it in a moment.

@xplshn not working
```
./Downloads/xfce4-power-manager-23_10_2024.dwfs.AppBundle
cat: /tmp/.pelfbundles/pbundle_xfce4powermanager23_10_2024xplshn17296706220342_/mounted/entrypoint: No such file or directory
/tmp/.pelfbundles/pbundle_xfce4powermanager23_10_2024xplshn17296706220342_/mounted/AppRun: 12: shift: can't shift that many
```
![image](https://github.com/user-attachments/assets/7a6269a2-ff87-4959-82de-819f8d29a4b0)
![image](https://github.com/user-attachments/assets/eb068e02-5f89-46f7-825b-e5251778d1e2)

**Comment by xplshn** [comment]
Yes, I'm aware of that, currently this repo is very W.I.P and I'm still making changes to make the AppBundles smaller and more portable :)

I'm waiting for this run to end https://github.com/xplshn/AppBundleHUB/actions/runs/11475499242/job/31934014142

**Comment by newyorkthink** [comment]
![image](https://github.com/user-attachments/assets/44c84f35-ee3a-4634-a2d3-0769284aa109)
![image](https://github.com/user-attachments/assets/d532d4d5-f551-492e-bdbf-ae8a38b5fe99)

**Comment by newyorkthink** [comment]
not work again

**Comment by xplshn** [comment]
You can use it btw, just pass "xfce4-power-manager" as argument, like this:
```
./xfce4-power-manager-23_10_2024.dwfs.AppBundle xfce4-power-manager
```

**Comment by newyorkthink** [comment]
> You can use it btw, just pass "xfce4-power-manager" as argument, like this:
> 
> ```
> ./xfce4-power-manager-23_10_2024.dwfs.AppBundle xfce4-power-manager
> ```

and you need add "xfce4-power-manager-setting" to the argu

![image](https://github.com/user-attachments/assets/1cf46032-cb1c-4395-8af6-ba69d61f017b)

because the i3 bar not show icon ,need open the xfce4-power-manager-setting to open the system tray

**Comment by newyorkthink** [comment]
![image](https://github.com/user-attachments/assets/3556849e-3aef-4845-a390-c40f72227993)

**Comment by newyorkthink** [comment]
and is not load /home/user/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-power-manager.xml config

**Comment by newyorkthink** [comment]
![image](https://github.com/user-attachments/assets/202c7db9-4672-42e5-963c-ee6136363ee4)
