### ISSUE TITLE
another app request: bluez , need enable systemctl bluetooth.

### ISSUE THREAD

**Issue by newyorkthink** [xplshn/AppBundleHUB#2]

**Comment by xplshn** [comment]
Is your request about the system daemon? Or UIs like blueman, etc?

**Comment by newyorkthink** [comment]
> Is your request about the system daemon? Or UIs like blueman, etc?

is the "bluez" package

**Comment by xplshn** [comment]
It is not possible to pack a kernel module as a portable executable
